"""
predict.py -- Inference module: image -> Fourier descriptors -> predicted linkage parameters.

Public API:
    load_model(model_path)  -> LinkagePredictorModel
    predict_linkage(image_path, model_path) -> dict

The feature normalisation stats (mean/std) are loaded from data/feature_norm.pt,
which is generated by generate_full_dataset.py. This ensures the inference input
is on the same scale the model was trained with.
"""

import os
import sys
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from model import LinkagePredictorModel
from image_parser import extract_path_from_image

PROJECT_ROOT  = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DEFAULT_MODEL = os.path.join(PROJECT_ROOT, "models", "best_model.pth")
NORM_PATH     = os.path.join(PROJECT_ROOT, "data", "feature_norm.pt")

_PARAM_KEYS   = ["norm_a", "norm_b", "norm_c", "norm_d", "norm_p", "p_angle"]


def load_model(model_path: str = DEFAULT_MODEL) -> LinkagePredictorModel:
    """Load and return the trained model in eval mode."""
    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"Model checkpoint not found: {model_path}\n"
            f"Run  python src/train_full.py  first."
        )
    model = LinkagePredictorModel(num_fourier_features=15, hidden_dim=256)
    model.load_state_dict(torch.load(model_path, weights_only=True, map_location="cpu"))
    model.eval()
    return model


def load_feature_norm():
    """Load per-feature mean and std from the training dataset stats."""
    if not os.path.exists(NORM_PATH):
        raise FileNotFoundError(
            f"Feature normalisation stats not found: {NORM_PATH}\n"
            f"Run  python src/generate_full_dataset.py  first."
        )
    norm = torch.load(NORM_PATH, weights_only=True)
    return norm["mean"].float(), norm["std"].float()


def predict_linkage(
    image_path: str,
    model_path: str = DEFAULT_MODEL,
) -> dict:
    """
    Read a hand-drawn path image and predict the four-bar CRANK-ROCKER parameters.

    Parameters
    ----------
    image_path : path to a PNG/JPG with a hand-drawn closed coupler trajectory.
    model_path : path to the trained model checkpoint.

    Returns
    -------
    dict with keys:
        norm_a, norm_b, norm_c, norm_d, norm_p  -- float, normalised link ratios
        p_angle                                  -- float, coupler angle in radians
        fd_tensor                                -- torch.Tensor[30], raw FD vector
        fd_tensor_norm                           -- torch.Tensor[30], normalised FD vector
    """
    model       = load_model(model_path)
    fd_mean, fd_std = load_feature_norm()

    fd_raw  = extract_path_from_image(image_path)          # [30] float32
    fd_norm = (fd_raw - fd_mean) / fd_std                  # z-score
    fd_norm = torch.clamp(fd_norm, -5.0, 5.0)             # same clip as training

    with torch.no_grad():
        raw = model(fd_norm.unsqueeze(0)).squeeze(0)       # [6]

    result = {key: float(raw[i]) for i, key in enumerate(_PARAM_KEYS)}
    result["fd_tensor"]      = fd_raw
    result["fd_tensor_norm"] = fd_norm
    return result
